"Template file"

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "nuget_package")  # @unused

def project_dotnet_repositories_nuget():
    " Nugets declaration "

    ### Generated by the tool
    nuget_package(
        name = "grpc.tools",
        package = "grpc.tools",
        version = "2.34.0",
        sha256 = "beb6cb841e389701774db1d66fe320a7a7aa4e15ba7f6893cc1a28ec6e003966",
        core_files = {
            "netcoreapp2.0": [
               "tools/linux_x64/grpc_csharp_plugin",
               "tools/linux_x64/protoc",
               "tools/linux_x86/grpc_csharp_plugin",
               "tools/linux_x86/protoc",
               "tools/macosx_x64/grpc_csharp_plugin",
               "tools/macosx_x64/protoc",
               "tools/macosx_x86/grpc_csharp_plugin",
               "tools/macosx_x86/protoc",
               "tools/windows_x64/grpc_csharp_plugin.exe",
               "tools/windows_x64/protoc.exe",
               "tools/windows_x86/grpc_csharp_plugin.exe",
               "tools/windows_x86/protoc.exe",
               "build/Grpc.Tools.props",
               "build/Grpc.Tools.targets",
               "build/_grpc/Grpc.CSharp.xml",
               "build/_grpc/_Grpc.Tools.props",
               "build/_grpc/_Grpc.Tools.targets",
               "build/_protobuf/Google.Protobuf.Tools.props",
               "build/_protobuf/Google.Protobuf.Tools.targets",
               "build/_protobuf/net45/Protobuf.MSBuild.dll",
               "build/_protobuf/net45/Protobuf.MSBuild.pdb",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.pdb",
               "build/_protobuf/Protobuf.CSharp.xml",
            ],
            "netcoreapp2.1": [
               "tools/linux_x64/grpc_csharp_plugin",
               "tools/linux_x64/protoc",
               "tools/linux_x86/grpc_csharp_plugin",
               "tools/linux_x86/protoc",
               "tools/macosx_x64/grpc_csharp_plugin",
               "tools/macosx_x64/protoc",
               "tools/macosx_x86/grpc_csharp_plugin",
               "tools/macosx_x86/protoc",
               "tools/windows_x64/grpc_csharp_plugin.exe",
               "tools/windows_x64/protoc.exe",
               "tools/windows_x86/grpc_csharp_plugin.exe",
               "tools/windows_x86/protoc.exe",
               "build/Grpc.Tools.props",
               "build/Grpc.Tools.targets",
               "build/_grpc/Grpc.CSharp.xml",
               "build/_grpc/_Grpc.Tools.props",
               "build/_grpc/_Grpc.Tools.targets",
               "build/_protobuf/Google.Protobuf.Tools.props",
               "build/_protobuf/Google.Protobuf.Tools.targets",
               "build/_protobuf/net45/Protobuf.MSBuild.dll",
               "build/_protobuf/net45/Protobuf.MSBuild.pdb",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.pdb",
               "build/_protobuf/Protobuf.CSharp.xml",
            ],
            "netcoreapp2.2": [
               "tools/linux_x64/grpc_csharp_plugin",
               "tools/linux_x64/protoc",
               "tools/linux_x86/grpc_csharp_plugin",
               "tools/linux_x86/protoc",
               "tools/macosx_x64/grpc_csharp_plugin",
               "tools/macosx_x64/protoc",
               "tools/macosx_x86/grpc_csharp_plugin",
               "tools/macosx_x86/protoc",
               "tools/windows_x64/grpc_csharp_plugin.exe",
               "tools/windows_x64/protoc.exe",
               "tools/windows_x86/grpc_csharp_plugin.exe",
               "tools/windows_x86/protoc.exe",
               "build/Grpc.Tools.props",
               "build/Grpc.Tools.targets",
               "build/_grpc/Grpc.CSharp.xml",
               "build/_grpc/_Grpc.Tools.props",
               "build/_grpc/_Grpc.Tools.targets",
               "build/_protobuf/Google.Protobuf.Tools.props",
               "build/_protobuf/Google.Protobuf.Tools.targets",
               "build/_protobuf/net45/Protobuf.MSBuild.dll",
               "build/_protobuf/net45/Protobuf.MSBuild.pdb",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.pdb",
               "build/_protobuf/Protobuf.CSharp.xml",
            ],
            "netcoreapp3.0": [
               "tools/linux_x64/grpc_csharp_plugin",
               "tools/linux_x64/protoc",
               "tools/linux_x86/grpc_csharp_plugin",
               "tools/linux_x86/protoc",
               "tools/macosx_x64/grpc_csharp_plugin",
               "tools/macosx_x64/protoc",
               "tools/macosx_x86/grpc_csharp_plugin",
               "tools/macosx_x86/protoc",
               "tools/windows_x64/grpc_csharp_plugin.exe",
               "tools/windows_x64/protoc.exe",
               "tools/windows_x86/grpc_csharp_plugin.exe",
               "tools/windows_x86/protoc.exe",
               "build/Grpc.Tools.props",
               "build/Grpc.Tools.targets",
               "build/_grpc/Grpc.CSharp.xml",
               "build/_grpc/_Grpc.Tools.props",
               "build/_grpc/_Grpc.Tools.targets",
               "build/_protobuf/Google.Protobuf.Tools.props",
               "build/_protobuf/Google.Protobuf.Tools.targets",
               "build/_protobuf/net45/Protobuf.MSBuild.dll",
               "build/_protobuf/net45/Protobuf.MSBuild.pdb",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.pdb",
               "build/_protobuf/Protobuf.CSharp.xml",
            ],
            "netcoreapp3.1": [
               "tools/linux_x64/grpc_csharp_plugin",
               "tools/linux_x64/protoc",
               "tools/linux_x86/grpc_csharp_plugin",
               "tools/linux_x86/protoc",
               "tools/macosx_x64/grpc_csharp_plugin",
               "tools/macosx_x64/protoc",
               "tools/macosx_x86/grpc_csharp_plugin",
               "tools/macosx_x86/protoc",
               "tools/windows_x64/grpc_csharp_plugin.exe",
               "tools/windows_x64/protoc.exe",
               "tools/windows_x86/grpc_csharp_plugin.exe",
               "tools/windows_x86/protoc.exe",
               "build/Grpc.Tools.props",
               "build/Grpc.Tools.targets",
               "build/_grpc/Grpc.CSharp.xml",
               "build/_grpc/_Grpc.Tools.props",
               "build/_grpc/_Grpc.Tools.targets",
               "build/_protobuf/Google.Protobuf.Tools.props",
               "build/_protobuf/Google.Protobuf.Tools.targets",
               "build/_protobuf/net45/Protobuf.MSBuild.dll",
               "build/_protobuf/net45/Protobuf.MSBuild.pdb",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll",
               "build/_protobuf/netstandard1.3/Protobuf.MSBuild.pdb",
               "build/_protobuf/Protobuf.CSharp.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.dependencyinjection.abstractions",
        package = "microsoft.extensions.dependencyinjection.abstractions",
        version = "3.0.3",
        sha256 = "af547daec0106f8e5dc6e0cfa48b5d584f772582262bcffef93d85fccaa5d1c3",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.dependencyinjection",
        package = "microsoft.extensions.dependencyinjection",
        version = "3.0.3",
        sha256 = "f28d4b8e4e667bcdc77c3c709508a7a703aeaa167a514938a16563f78135a359",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll",
               "lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.logging.abstractions",
        package = "microsoft.extensions.logging.abstractions",
        version = "3.0.3",
        sha256 = "5056b08020216cde470ad272dfd5cee2ccf937f3ff672aecd2eaab40773848f2",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.primitives",
        package = "microsoft.extensions.primitives",
        version = "3.0.3",
        sha256 = "ee8e05fb616481bd18bb6876cbe7ea16256db8d43c68267692f68b44a7c9f423",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Primitives.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.configuration.abstractions",
        package = "microsoft.extensions.configuration.abstractions",
        version = "3.0.3",
        sha256 = "35102c6f4684c05ad948633898d62ef3b9860268e00d758bdb07c8f38df686a2",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.primitives//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.primitives//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.primitives//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.primitives//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.primitives//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Abstractions.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.configuration",
        package = "microsoft.extensions.configuration",
        version = "3.0.3",
        sha256 = "a87fa333fded2685868248c79121b710306229920cafdbe39d3f2361cad83c3a",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.configuration.abstractions//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.configuration.abstractions//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.configuration.abstractions//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.configuration.abstractions//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.configuration.abstractions//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.configuration.binder",
        package = "microsoft.extensions.configuration.binder",
        version = "3.0.3",
        sha256 = "79815ab869c8f33225f3ab6516b27a481970ab0c9233343ee636f64df704c97f",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.configuration//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.configuration//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.configuration//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.configuration//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.configuration//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Configuration.Binder.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.options",
        package = "microsoft.extensions.options",
        version = "3.0.3",
        sha256 = "c09fff9677fe7457211e8a6ac5abc9ba9b5815b63d6f103871b08d3ffa180453",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Options.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Options.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.0_core",
               "@microsoft.extensions.primitives//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.1_core",
               "@microsoft.extensions.primitives//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.2_core",
               "@microsoft.extensions.primitives//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.0_core",
               "@microsoft.extensions.primitives//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.1_core",
               "@microsoft.extensions.primitives//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Options.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Options.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Options.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Options.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Options.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Options.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Options.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Options.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.logging",
        package = "microsoft.extensions.logging",
        version = "3.0.3",
        sha256 = "c1c09caed1dd2a8350bf2e23763c2a4f55eec039a1fe24ec6e8bfb98e632d04f",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Logging.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Logging.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.configuration.binder//:netcoreapp2.0_core",
               "@microsoft.extensions.dependencyinjection//:netcoreapp2.0_core",
               "@microsoft.extensions.logging.abstractions//:netcoreapp2.0_core",
               "@microsoft.extensions.options//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.configuration.binder//:netcoreapp2.1_core",
               "@microsoft.extensions.dependencyinjection//:netcoreapp2.1_core",
               "@microsoft.extensions.logging.abstractions//:netcoreapp2.1_core",
               "@microsoft.extensions.options//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.configuration.binder//:netcoreapp2.2_core",
               "@microsoft.extensions.dependencyinjection//:netcoreapp2.2_core",
               "@microsoft.extensions.logging.abstractions//:netcoreapp2.2_core",
               "@microsoft.extensions.options//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.configuration.binder//:netcoreapp3.0_core",
               "@microsoft.extensions.dependencyinjection//:netcoreapp3.0_core",
               "@microsoft.extensions.logging.abstractions//:netcoreapp3.0_core",
               "@microsoft.extensions.options//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.configuration.binder//:netcoreapp3.1_core",
               "@microsoft.extensions.dependencyinjection//:netcoreapp3.1_core",
               "@microsoft.extensions.logging.abstractions//:netcoreapp3.1_core",
               "@microsoft.extensions.options//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Logging.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Logging.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Logging.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Logging.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Logging.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Logging.xml",
            ],
        },
    )
    nuget_package(
        name = "microsoft.extensions.http",
        package = "microsoft.extensions.http",
        version = "3.0.3",
        sha256 = "2118d0329b5be54b1edc7e187235429b1b0cb7c94ae08b65af245725508b8e3e",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
            "netcoreapp3.0": "lib/netcoreapp3.0/Microsoft.Extensions.Http.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Microsoft.Extensions.Http.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.0_core",
               "@microsoft.extensions.logging//:netcoreapp2.0_core",
               "@microsoft.extensions.options//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.1_core",
               "@microsoft.extensions.logging//:netcoreapp2.1_core",
               "@microsoft.extensions.options//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp2.2_core",
               "@microsoft.extensions.logging//:netcoreapp2.2_core",
               "@microsoft.extensions.options//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.0_core",
               "@microsoft.extensions.logging//:netcoreapp3.0_core",
               "@microsoft.extensions.options//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@microsoft.extensions.dependencyinjection.abstractions//:netcoreapp3.1_core",
               "@microsoft.extensions.logging//:netcoreapp3.1_core",
               "@microsoft.extensions.options//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Http.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Http.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Microsoft.Extensions.Http.dll",
               "lib/netstandard2.0/Microsoft.Extensions.Http.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Http.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Http.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Microsoft.Extensions.Http.dll",
               "lib/netcoreapp3.0/Microsoft.Extensions.Http.xml",
            ],
        },
    )
    nuget_package(
        name = "system.buffers",
        package = "system.buffers",
        version = "4.4.0",
        sha256 = "293c408586b0146d95e555f58f0de9cf1dc8ad05d1827d53b2f8233e0c406ea0",
    )
    nuget_package(
        name = "system.diagnostics.diagnosticsource",
        package = "system.diagnostics.diagnosticsource",
        version = "4.5.1",
        sha256 = "81910346fd2fd0001ab90dfa0565e4264dc62d6d2c607e903f16b4a7697c0dc9",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
            "netcoreapp2.1": "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
            "netcoreapp2.2": "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
            "netcoreapp3.0": "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
            "netcoreapp3.1": "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll",
               "lib/netstandard1.3/System.Diagnostics.DiagnosticSource.xml",
            ],
        },
    )
    nuget_package(
        name = "system.numerics.vectors",
        package = "system.numerics.vectors",
        version = "4.4.0",
        sha256 = "6ae5d02b67e52ff2699c1feb11c01c526e2f60c09830432258e0809486aabb65",
    )
    nuget_package(
        name = "system.runtime.compilerservices.unsafe",
        package = "system.runtime.compilerservices.unsafe",
        version = "4.5.2",
        sha256 = "f1e5175c658ed8b2fbb804cc6727b6882a503844e7da309c8d4846e9ca11e4ef",
        core_lib = {
            "netcoreapp2.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_ref = {
            "netcoreapp2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.1": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.2": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
        },
    )
    nuget_package(
        name = "system.memory",
        package = "system.memory",
        version = "4.5.3",
        sha256 = "0af97b45b45b46ef6a2b37910568dabd492c793da3859054595d523e2a545859",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/System.Memory.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/System.Memory.dll",
               "lib/netstandard2.0/System.Memory.xml",
            ],
        },
    )
    nuget_package(
        name = "google.protobuf",
        package = "google.protobuf",
        version = "3.14.0",
        sha256 = "cbf79fe9b04cd8742a255f88e5961a3d075bfa6367012ce88e056e6e0c8dc523",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Google.Protobuf.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.memory//:netcoreapp2.0_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@system.memory//:netcoreapp2.1_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@system.memory//:netcoreapp2.2_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@system.memory//:netcoreapp3.0_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@system.memory//:netcoreapp3.1_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.core.api",
        package = "grpc.core.api",
        version = "2.34.0",
        sha256 = "abb9ac6e5ee7d46dafb0dbf83ed47f504d328359dfad6393517f4a6822da6d33",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.memory//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@system.memory//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@system.memory//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@system.memory//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@system.memory//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.net.common",
        package = "grpc.net.common",
        version = "2.34.0",
        sha256 = "3a76af2ab03d0ad881b7a3cc6f457a618f254caddbacb5973eee3e194906b54d",
    )
    nuget_package(
        name = "grpc.aspnetcore.server",
        package = "grpc.aspnetcore.server",
        version = "2.34.0",
        sha256 = "3d9c7cdca8f16e06d7b5959511ca101380eaf77e95a7fe8212893284bddb4c71",
        core_lib = {
            "netcoreapp3.0": "lib/netcoreapp3.0/Grpc.AspNetCore.Server.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Grpc.AspNetCore.Server.dll",
        },
        core_deps = {
            "netcoreapp3.0": [
               "@grpc.net.common//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@grpc.net.common//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.dll",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.pdb",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.dll",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.pdb",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.net.client",
        package = "grpc.net.client",
        version = "2.34.0",
        sha256 = "b8f7cb9b2427147055a154ab56f71cf200d3a2e741de332f375108fde6fd1892",
    )
    nuget_package(
        name = "grpc.net.clientfactory",
        package = "grpc.net.clientfactory",
        version = "2.34.0",
        sha256 = "2c4f829bba9848c94b71dfa99555ea5df2ecc6726a670983d5ec95791a510e0d",
    )
    nuget_package(
        name = "grpc.aspnetcore.server.clientfactory",
        package = "grpc.aspnetcore.server.clientfactory",
        version = "2.34.0",
        sha256 = "c47629948ad66d5d7d23554af6d3d804ed275ce1262c36cbbfb1d2b1fad82d21",
        core_lib = {
            "netcoreapp3.0": "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.dll",
            "netcoreapp3.1": "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.dll",
        },
        core_deps = {
            "netcoreapp3.0": [
               "@grpc.aspnetcore.server//:netcoreapp3.0_core",
               "@grpc.net.clientfactory//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@grpc.aspnetcore.server//:netcoreapp3.1_core",
               "@grpc.net.clientfactory//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp3.0": [
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.dll",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.pdb",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.dll",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.pdb",
               "lib/netcoreapp3.0/Grpc.AspNetCore.Server.ClientFactory.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.aspnetcore",
        package = "grpc.aspnetcore",
        version = "2.34.0",
        sha256 = "7641885b98334b54edc1cdcf5da3ac121ee76eb3ecf7d0fd8bd739e504864295",
        core_deps = {
            "netcoreapp3.0": [
               "@grpc.aspnetcore.server.clientfactory//:netcoreapp3.0_core",
               "@google.protobuf//:netcoreapp3.0_core",
               "@grpc.tools//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@grpc.aspnetcore.server.clientfactory//:netcoreapp3.1_core",
               "@google.protobuf//:netcoreapp3.1_core",
               "@grpc.tools//:netcoreapp3.1_core",
            ],
        },
    )
    ### End of generated by the tool
    return
