on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 4.0.0

    - name: Build
      run: "bazelisk build //:server.exe"